### ISSUE TITLE
negative sleep times in dequeue

### ISSUE THREAD

**Issue by toratora** [Grinnz/Minion-Backend-SQLite#12]
getting `Time::HiRes::usleep(-1106.02): negative time not invented yet at C:/strawberry/perl/site/lib/Minion/Backend/SQLite.pm line 39.` after recent change in 2.004. This is on Win7 perl 5.20.1.

I monkey patched in the following which seems to work:

```
sub dequeue {
  my ($self, $id, $wait, $options) = @_;
  my $job = $self->_try($id, $options);
  unless ($job) {
    my $int   = $self->dequeue_interval;
    my $end   = steady_time + $wait;
    my $sleep = $wait;
    usleep(min($int, $sleep) * 1000000)
      until ($sleep = $end - steady_time) <= 0
      or $job = $self->_try($id, $options);
  }
  return $job || $self->_try($id, $options);
}
```

**Comment by Grinnz** [comment]
I see, it seems to be a race between the two calls to steady_time. Thanks for the fix.

**Comment by Grinnz** [comment]
Patched in https://github.com/Grinnz/Minion-Backend-SQLite/commit/bdc17a43203962481f87989d5af7a871f2da4347
