### ISSUE TITLE
failed install on mac

### ISSUE THREAD

**Issue by hotsnow** [Grinnz/Minion-Backend-SQLite#2]
perl: v5.18.2
Minion: 4.01
## Minion::Backend::SQLite: 0.002

cpanm (App::cpanminus) 1.7039 on perl 5.018002 built for darwin-thread-multi-2level
Work directory is /Users/hotsnow/.cpanm/work/1447428948.37805
You have make /usr/bin/make
You have LWP 6.05
You have /usr/bin/tar: bsdtar 2.8.3 - libarchive 2.8.3
You have /usr/bin/unzip
Searching Minion::Backend::SQLite on mirror http://mirrors.163.com/cpan ...
Downloading index file http://mirrors.163.com/cpan/modules/02packages.details.txt.gz ...
--> Working on Minion::Backend::SQLite
Fetching http://mirrors.163.com/cpan/authors/id/D/DB/DBOOK/Minion-Backend-SQLite-0.002.tar.gz
-> OK
Unpacking Minion-Backend-SQLite-0.002.tar.gz
Entering Minion-Backend-SQLite-0.002
Checking configure dependencies from META.json
Checking if you have Module::Build::Tiny 0.034 ... Yes (0.034)
Configuring Minion-Backend-SQLite-0.002
Running Build.PL
Creating new 'Build' script for 'Minion-Backend-SQLite' version '0.002'
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have Sys::Hostname 0 ... Yes (1.17)
Checking if you have Mojolicious 6.0 ... Yes (6.25)
Checking if you have Test::More 0.88 ... Yes (0.98)
Checking if you have DBI 0.88 ... Yes (1.634)
Checking if you have Minion 3.02 ... Yes (4.01)
Checking if you have Time::HiRes 0 ... Yes (1.9725)
Checking if you have Mojo::SQLite 0.018 ... Yes (0.018)
Building and testing Minion-Backend-SQLite-0.002
cp lib/Minion/Backend/SQLite.pm blib/lib/Minion/Backend/SQLite.pm
t/author-pod-coverage.t .. skipped: these tests are for testing by the author
t/author-pod-syntax.t .... skipped: these tests are for testing by the author
Can't locate object method "attempts" via package "Minion::Job" at t/sqlite.t line 472, <DATA> line 694.
# Tests were run but no plan was declared and done_testing() was not seen.

t/sqlite.t ............... 
Dubious, test returned 2 (wstat 512, 0x200)
All 237 subtests passed 
t/sqlite_lite_app.t ...... ok
## Test Summary Report

t/sqlite.t             (Wstat: 512 Tests: 237 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
Files=4, Tests=252,  1 wallclock secs ( 0.04 usr  0.01 sys +  0.60 cusr  0.20 csys =  0.85 CPU)
Result: FAIL
-> FAIL Installing Minion::Backend::SQLite failed. See /Users/hotsnow/.cpanm/work/1447428948.37805/build.log for details. Retry with --force to force install it.

**Comment by Grinnz** [comment]
The error is actually the line about "attempts", which has been removed in the latest version of Minion. This will be fixed shortly. Thanks for the report

**Comment by Grinnz** [comment]
Fixed in 0.003
