### ISSUE TITLE
libminion-backend-sqlite-perl: test failures with SQLite 3.37

### ISSUE THREAD

**Issue by gregoa** [Grinnz/Minion-Backend-SQLite#20]
We have the following bug reported to the Debian package of
Minion-Backend-SQLite, c.f. https://bugs.debian.org/1004143

It doesn't seem to be a bug in the packaging, so you may want to take
a look. Thanks!

------8<-----------8<-----------8<-----------8<-----------8<-----

```
Source: libminion-backend-sqlite-perl
Version: 5.0.4-1
Severity: serious
Tags: upstream ftbfs
Justification: fails to build from source

As seen on ci.debian.net:
https://ci.debian.net/packages/libm/libminion-backend-sqlite-perl/
and reproduced locally, libminion-backend-sqlite-perl's tests fail
since a few weeks, presumably sind sqlite3 3.37.x hit unstable:


    # No tests run!

DBD::SQLite::db do failed: SQL logic error at /usr/share/perl5/Mojo/SQLite.pm line 118.
 at /usr/share/perl5/Mojo/SQLite.pm line 118.
t/sqlite.t ............. 
    1..0
not ok 1 - No tests run for subtest "Nothing to repair"
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/1 subtests 
    # No tests run!

DBD::SQLite::db do failed: SQL logic error at /usr/share/perl5/Mojo/SQLite.pm line 118.
 at /usr/share/perl5/Mojo/SQLite.pm line 118.
t/sqlite_worker.t ...... 
    1..0
not ok 1 - No tests run for subtest "Basics"
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/1 subtests 

Test Summary Report
- -------------------
t/sqlite.t           (Wstat: 65280 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/sqlite_worker.t    (Wstat: 65280 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=3, Tests=3,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.53 cusr  0.07 csys =  0.63 CPU)
Result: FAIL



Cheers,
gregor


```
------8<-----------8<-----------8<-----------8<-----------8<-----

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by stoecker** [comment]
We had the same issue for openSUSE. Reason is that json extension aren't included in the code of DBD::SQLite.

My suggestion would be to add a test for json_valid() in this package, so that the issue is detected. Or better, don't rely on json extension :-)

Otherwise for Debian my suggestion would be to go back to included sqlite3.c in DBD::SQLite.

**Comment by Grinnz** [comment]
Weird, I would consider it a bug if the distro packagers have it depend on a sqlite package which doesn't provide the features that DBD::SQLite does.

**Comment by kraih** [comment]
Have to agree with @Grinnz on this. If packagers don't provide the same features as vanilla `DBD::SQLite` provides then that is a bug.

**Comment by stoecker** [comment]
I think we must investigate WHY the json stuff is not available. After checking the docs it should be also in the system libs.

**Comment by stoecker** [comment]
It seems a bit more complex:

```
use Mojo::SQLite;
use DBI;

my $query1 = "create table if not exists t (host text)";
my $query2 = "alter table t add column c text check(json_valid(c)) default '[]'";

my $dbh = DBI->connect("dbi:SQLite:dbname=a.db","","");
$dbh->do($query1);
$dbh->do($query2);

my $sql = Mojo::SQLite->new->from_filename("t.db");
my $db = $sql->db;
$db->dbh->do($query1);
$db->dbh->do($query2);                    # <---- dies here
```

**Comment by Martchus** [comment]
Looks like an incompatibility in `Mojo::SQLite` then. You could run with `DBI_TRACE=1` and compare whether there's a difference in the output.

**Comment by stoecker** [comment]
Further reduced:
```
use DBI;
use DBD::SQLite::Constants ":database_connection_configuration_options";

my $query1 = "create table if not exists t (host text)";
my $query2 = "alter table t add column c text check(json_valid(c)) default '[]'";

my $dbh = DBI->connect("dbi:SQLite:dbname=a.db","","");
$dbh->sqlite_db_config(SQLITE_DBCONFIG_DQS_DML, 0);
$dbh->do($query1);
$dbh->do($query2); # <---- dies here

```
 SQLITE_DBCONFIG_DQS_DML disables the double quoting feature, but there is no double quoting here. Strange. Bug in newer SQLITE?

**Comment by Martchus** [comment]
Good catch, could be a bug introduced in a newer SQLite version, indeed.

**Comment by gregoa** [comment]
Thanks for all the input.

What I can add is that I can't reproduce the test failures anymore on Debian/unstable; so my current _guess_ is that this was a problem with sqlite3 3.37.x (either upstream or in Debian), and with at least 3.38.1 it seems to work again.

**Comment by stoecker** [comment]
We'll see. 3.38.1 isn't yet through in openSUSE, but it's on the way :-)

**Comment by kraih** [comment]
This does highlight the problem of not using the SQLite that ships with `DBD::SQLite` though. All 3rd party modules will expect the exact feature set provided by that version. And it only gets more complicated when modules depend on specific versions of `DBD::SQLite`. We see this every time a distribution splits up a Perl module. It only leads to more problems down the road.

**Comment by perlpunk** [comment]
Just mentionig the related discussion where I posted my initial reproducer https://build.opensuse.org/request/show/960440#comment-1595997, that @stoecker was able to reduce more.

**Comment by stoecker** [comment]
Verified for openSUSE: With sqlite 3.38.1 it builds fine.

**Comment by Vogtinator** [comment]
I was curious what actually caused this and did a quick bisect of sqlite. Turns out this is actually unrelated to JSON: https://sqlite.org/forum/forumpost/3c1a00b66fca81fe

FWICT, introduced by https://github.com/sqlite/sqlite/commit/b4d9b2b5376e6 and fixed by https://github.com/sqlite/sqlite/commit/72e30421c8

**Comment by gregoa** [comment]
I guess this issue can be closed, as the problem was not in this distribution but in SQLite?
Thanks everybody for tracking it down.

**Comment by Martchus** [comment]
Yes, can be closed from openSUSE's side as well.

**Comment by gregoa** [comment]
Alright, closing this issue.

Thanks again for all the input, and sorry for the noise to our upstream authors.
