### ISSUE TITLE
DB!

### ISSUE THREAD

**Issue by kostyaten** [Grinnz/Minion-Backend-SQLite#3]
plugin Minion => { SQLite => 'sqlite:test.db' };

plugin Minion => { SQLite => 'sqlite:/var/db.db' }; # Not work!
plugin Minion => { SQLite => '/var/db.db' }; # Not work!

How to do?

**Comment by Grinnz** [comment]
See https://metacpan.org/pod/Mojo::SQLite#from_string -- those should work, but try sqlite:////var/db.db or file:///var/db.db

Of course you will need to make sure you have write permission to the directory which the database is stored in, so that SQLite can make temp files.
