### ISSUE TITLE
Error: file is encrypted or is not a database

### ISSUE THREAD

**Issue by bfaist** [Grinnz/Minion-Backend-SQLite#5]
The SQLite backend seems to run OK but I can not view the tables with sqlite3 version 3.6.20.

CentOS 6
Mojo::SQLite:  0.021
DBD::SQLite:  1.50

```
$sqlite3 minion.db
SQLite version 3.6.20
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> .tables
Error: file is encrypted or is not a database
sqlite> .quit
```

```
my $minion = Minion->new(SQLite => "sqlite:minion.db");

$minion->add_task(simple_task => sub {
     my $job = shift;

     print "START simple_task\n";
     open my $debug_fh, '>', 'minion_debug.txt';
     print {$debug_fh} Dumper($job);
     close $debug_fh;
     sleep(2);
     print "END simple_task\n";
});

$minion->enqueue('simple_task');
$minion->perform_jobs();
```

**Comment by bfaist** [comment]
This works fine if I use the 3.11.0 version of the sqlite3 executable.  Will close.

**Comment by Grinnz** [comment]
For reference, DBD::SQLite (which is used by Mojo::SQLite and thus Minion::Backend::SQLite) bundles its own version of sqlite3 (currently 3.10.2). Using a significantly lower version to access the database is likely to run into issues; for example, WAL mode, which Mojo::SQLite enables on its databases by default, requires 3.7.0 or higher.
