### ISSUE TITLE
Jobs are not executed necessarilly in the order they were created (even with one worker)

### ISSUE THREAD

**Issue by akarelas** [Grinnz/Minion-Backend-SQLite#9]
As one can see in [this line](https://metacpan.org/source/DBOOK/Minion-Backend-SQLite-0.007/lib/Minion/Backend/SQLite.pm#L244), the order is on priority, created, instead of priority, id.

This was the case on the Pg backend as well, but recently kraih changed to priority, id, as you can see [here](https://github.com/kraih/minion/blob/master/lib/Minion/Backend/Pg.pm#L234).

I think it should be changed on the SQLite backend as well, thanks!

**Comment by Grinnz** [comment]
Fixed in 0.008, thanks!
